services:
  mine-server:
    image: ubuntu:latest
    container_name: Mineflared
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    working_dir: /app
    command: ["bash", "build.sh"]
